name: Yugen.Toolkit.Standard.Core/Build, Pack and Publish Nuget
on:
  push:
    branches:    
      - master   

jobs:   
  build_pack_publish:
    runs-on: windows-latest
    name: Build
    steps:
    - uses: actions/checkout@v1   
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: MSBuild Restore
      run: msbuild Yugen.Toolkit.Standard.Core\Yugen.Toolkit.Standard.Core.csproj /p:Configuration="Release" /t:restore     

    - name: MSBuild Build
      run: msbuild Yugen.Toolkit.Standard.Core\Yugen.Toolkit.Standard.Core.csproj /p:Configuration="Release"

    - name: MSBuild Pack
      run: msbuild Yugen.Toolkit.Standard.Core\Yugen.Toolkit.Standard.Core.csproj /p:Configuration="Release" /t:pack 
    #-p:PackageVersion=1.0.2 

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
        
    - name: Nuget SetAPIKey
      run: nuget setApiKey ${{ secrets.NUGET_KEY }}

    - name: Nuget Push
      run: nuget push Yugen.Toolkit.Standard.Core\bin\Release\*.nupkg -Source https://api.nuget.org/v3/index.json
      continue-on-error: true
    
    - name: GH Nuget Add Source
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/panda-sharp/index.json" -UserName panda-sharp -Password ${{ secrets.PACKAGES_TOKEN }}

    - name: GH Nuget SetAPIKey
      run: nuget setApiKey ${{ secrets.PACKAGES_TOKEN }} -Source "GitHub"

    - name: GH Nuget Push
      run: nuget push Yugen.Toolkit.Standard.Core\bin\Release\*.nupkg -Source "GitHub"
