name: Yugen.Toolkit.Uwp.Controls/Build, Pack and Publish Nuget
on:
  push:
    branches:    
      - master   

jobs:   
  build_pack_publish:
    runs-on: windows-latest
    name: Build
    steps:
    - uses: actions/checkout@v1   
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: MSBuild Restore
      run: msbuild Yugen.Toolkit.Uwp.Controls\Yugen.Toolkit.Uwp.Controls.csproj /p:Configuration="Release" /t:restore     

    - name: MSBuild Build
      run: msbuild Yugen.Toolkit.Uwp.Controls\Yugen.Toolkit.Uwp.Controls.csproj /p:Configuration="Release"
      
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      
    - name: Nuget Pack
      run: nuget pack Yugen.Toolkit.Uwp.Controls\Yugen.Toolkit.Uwp.Controls.csproj -properties Configuration=Release
        
    - name: Nuget SetAPIKey
      run: nuget setApiKey ${{ secrets.NUGET_KEY }}

    - name: Nuget Push
      run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json
      continue-on-error: true

    - name: GH Nuget Add Source
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/panda-sharp/index.json" -UserName panda-sharp -Password ${{ secrets.PACKAGES_TOKEN }}
      
    - name: GH Nuget SetAPIKey
      run: nuget setApiKey ${{ secrets.PACKAGES_TOKEN }} -Source "GitHub"      
    
    - name: GH Nuget Push
      run: nuget push *.nupkg -Source "GitHub"
      
